const bank = {
    mapName: "Bank",
    floors: [
        {
            name: "Basement",
            callouts: [
                "Sewer",
                "Tunnel",
                "Server",
                "Server Rack",
                "Blue Stairs",
                "Bottom Square",
                "CCTV",
                "Locker Hall",
                "Ramp",
                "Garage",
                "Bottom Main Stairs",
                "Red",
                "Gold",
                "Cash",
                "Vault",
                "Vault Drop",
                "Lockers",
                "Elevator Lobby",
                "Elevator Drop",
            ],
        },

        {
            name: "1st Floor",
            callouts: [
                "Electrical",
                "Bottom Square",
                "Blue Stairs",
                "Skylight Stairs",
                "Staff",
                "Printer",
                "Open Area",
                "Admin",
                "Archives",
                "Tellers",
                "Elevator Hall",
                "Circle Desk",
                "Lobby",
                "ATM",
                "Spiral Stairs",
                "Side Office",
                "Elevator Hatch",
                "Main Stairs",
            ],
        },

        {
            name: "2nd Floor",
            callouts: [
                "Balcony",
                "Top Square",
                "Skylight Stairs",
                "Janitor Hall",
                "Long Hall",
                "Stock",
                "Janitor",
                "CEO",
                "Couches",
                "Double",
                "Long Desk",
                "Front Desk",
                "Top Spiral",
                "Spiral Stairs",
                "Top Main",
                "Main Stairs",
                "Banana",
            ],
        },
    ],
};

export default bank;
