const border = {
    mapName: "Border",
    floors: [
        {
            name: "1st Floor",
            callouts: [
                "West Main",
                "Server",
                "Workshop",
                "Ventilation",
                "Main Stairs",
                "Main Stairs Bottom",
                "Blue Lobby",
                "Blue Lobby Desk",
                "Bathroom",
                "Tellers Soda",
                "Tellers",
                "Bathroom Hall",
                "Customs",
                "Customs Mini",
                "Customs Default",
                "Customs Belt",
                "Jail Connector",
                "Jail",
                "Jail Breach",
                "Supply",
                "Supply Window",
                "Waiting",
                "Passport",
                "Bottom East Stairs",
                "East Stairs",
                "Top East Stairs",
                "Waiting Half Wall",
            ],
        },

        {
            name: "2nd Floor",
            callouts: [
                "Top East Stairs",
                "Long",
                "Office",
                "Office Paint",
                "East Balcony",
                "Office Triple Wall",
                "Office Printer",
                "Fountain",
                "Archives",
                "Crash Balcony",
                "Crash Stairs",
                "Archives Desk",
                "Armory",
                "Sandwich",
                "Armory Half Wall",
                "Armory Breach",
                "Armory Mini",
                "Armory Beeps",
                "Main Stairs",
                "Short",
                "90",
                "Break",
                "Waiting Balcony",
                "CCTV",
                "CC Banana",
                "CC Box",
                "AC Balcony",
            ],
        },
    ],
};

export default border;
