const chalet = {
    mapName: "Chalet",
    floors: [
        {
            name: "Basement",
            callouts: [
                "Garage Closet / Main Garage Entrance",
                "Main Garage",
                "Garage Wall",
                "Wine Hall",
                "Wine Stairs",
                "West Main",
                "Red",
                "Trench",
                "Wine Desk",
                "Wine Bottles",
                "Wine Barrels",
                "Blue Tarps",
                "Blue 90",
                "Blue Hall",
                "Blue Stairs",
                "Landing / Gaming Room Hallway",
                "Snow Garage",
                "Connector / Storage",
                "Garage Stairs",
                "Lobby",
                "Snow mobiles",
                "Wine Shelf",
            ],
        },

        {
            name: "1st Floor",
            callouts: [
                "Lobby",
                "Lobby Stairs",
                "Top Lobby Long",
                "Garage Stairs",
                "Snowmobile Balcony",
                "Bar",
                "Bar Desk",
                "Bar Stock",
                "Games",
                "Games Corner",
                "Games Window",
                "Games Hall",
                "Landing",
                "Mud",
                "Mud Window",
                "Bar Hall",
                "Dining Hall",
                "Dining",
                "Dining Half Wall",
                "Kitchen",
                "Kitchen Desk",
                "Kitchen Hall",
                "West Main",
                "West Main Window",
                "Trophy",
                "Trophy Stairs",
                "Solarium",
            ],
        },

        {
            name: "2nd Floor",
            callouts: [
                "Office Balcony",
                "Top Lobby Short",
                "Top Lobby Long",
                "Lobby Stairs",
                "Library",
                "Sandwich",
                "Library Balcony South",
                "Library Balcony West",
                "Library Closet",
                "Library Hall",
                "Library Stairs",
                "Piano",
                "Office",
                "Office Stairs",
                "Office Half Wall",
                "Piano Balcony",
                "Piano Hall",
                "Bathroom",
                "Solarium",
                "Trophy",
                "Trophy Stairs",
                "Bedroom",
                "Bedroom Closet",
                "Trench",
            ],
        },
    ],
};

export default chalet;
