const clubhouse = {
    mapName: "Clubhouse",
    floors: [
        {
            name: "Basement",
            callouts: [
                "Container",
                "Dirt",
                "Arsenal",
                "Back Arsenal",
                "Boxes",
                "Blue",
                "Generator",
                "Oil Pit Hall",
                "Oil Pit",
                "Blue Stairs Bottom",
                "Blue Stairs",
                "Dummies",
                "Long (Basement Hallway)",
                "Church",
                "Jukebox",
                "Motor",
                "Main Stairs Bottom",
                "Main Stairs",
                "Short",
                "Church Bar",
            ],
        },

        {
            name: "1st Floor",
            callouts: [
                "Garage",
                "Blue Box",
                "Bikes",
                "Garage Stairs",
                "Catwalk",
                "Bottom Red",
                "Lounge",
                "Stock",
                "Storage",
                "Blue Stairs",
                "Red Stairs",
                "Bar Main Entry",
                "Bar Stage",
                "Bar",
                "Bar Desk",
                "Pool Connector",
                "Pool Table",
                "Strip Hall",
                "Strip",
                "Strip Drop",
                "Strip South Entry",
                "Strip West Entry",
                "Toilets",
                "Kitchen Hall",
                "Kitchen",
                "Freezer",
                "Main Stairs",
            ],
        },

        {
            name: "2nd Floor",
            callouts: [
                "Garage Stairs",
                "Catwalk Long",
                "Catwalk Short",
                "Catwalk 90",
                "CCTV",
                "CC Breach",
                "Top Red",
                "Red Stairs",
                "Cash",
                "Construction",
                "Construction Breach",
                "Bedroom",
                "Bathroom",
                "Bedroom Hall",
                "Main Stairs",
                "Gym Hall",
                "Jacuzzi Balcony",
                "Gym",
                "Bedroom Balcony",
                "Gym Window",
                "Logistics",
                "Gold",
                "Logistic Wall",
                "CC Window",
            ],
        },
    ],
};

export default clubhouse;
