const coastline = {
    mapName: "Coastline",
    floors: [
        {
            name: "1st Floor",
            callouts: [
                "Lobby",
                "White Stairs",
                "Back Lobby",
                "Lobby Desk",
                "Bathroom",
                "Service",
                "Service Entrance",
                "Kitchen",
                "Sunrise Hall",
                "Cool Vibes",
                "Trash",
                "Kitchen Hall",
                "Sunrise",
                "Sunrise Desk",
                "Sunrise Closet",
                "Sunrise Couch",
                "Courtyard",
                "Blue Bar",
                "Office",
                "Security Connector",
                "Security",
            ],
        },

        {
            name: "2nd Floor",
            callouts: [
                "Lobby",
                "White Stairs",
                "Top White",
                "Theater Hall",
                "Theater",
                "Penthouse",
                "Penthouse Bed",
                "Penthouse Toilet",
                "Hall of Fame",
                "VIP",
                "VIP Balcony",
                "VIP Hall",
                "90",
                "Theater Hall",
                "Luggage",
                "Aqua",
                "Aqua Desk",
                "Billiards",
                "Billiards Bar",
                "Vases",
                "Cool Vibes",
                "Hookah",
                "Hookah Balcony",
                "Aqua Balcony",
            ],
        },
    ],
};

export default coastline;
