const consulate = {
    mapName: "Consulate",
    floors: [
        {
            name: "Basement",
            callouts: [
                "White Van / Side",
                "Pillar",
                "Metal Box",
                "Pipes",
                "Yellow Stairs",
                "Yellow Soda",
                "Default Cam",
                "Security Hall",
                "Security",
                "Kitchen",
                "Brown Box",
                "Glow Sticks",
                "Locker Hall",
                "Basement Spiral",
                "Storage",
                "Electrical",
                "Archives",
                "Server Racks",
                "Blue Hall",
                "Harry Potter",
                "Red",
                "Visa Stairs",
                "Visa Stairs Soda",
                "Black Car",
            ],
        },

        {
            name: "1st Floor",
            callouts: [
                "Lobby",
                "Lobby Closet",
                "Circle Desk",
                "Ante",
                "Bathroom",
                "Piano",
                "Piano Desk",
                "Yellow Soda",
                "Yellow Stairs",
                "Zulu Hall",
                "Zulu Windows",
                "Statue",
                "Spiral Stairs",
                "Tellers Hall",
                "Tellers",
                "Visa Entrance",
                "Visa",
                "Visa Stairs Soda",
                "Visa Stairs",
            ],
        },

        {
            name: "2nd Floor",
            callouts: [
                "Yellow Stairs",
                "Yellow Soda",
                "Top Yellow",
                "Front Desk",
                "CEO",
                "CEO Front Desk",
                "CEO Closet",
                "Bathroom",
                "Connector",
                "Reading",
                "Visa Stairs",
                "Short Desk",
                "Middle Admin",
                "South Admin",
                "North Admin",
                "Copy",
                "Break Room",
                "Short Desk",
                "Double Soda",
                "Long Desk",
                "Top Spiral",
                "Spiral Stairs",
                "Meeting",
                "Balcony",
            ],
        },
    ],
};

export default consulate;
