const kanal = {
    mapName: "Kanal",
    floors: [
        {
            name: "Basement",
            callouts: [
                "Trench",
                "Basement Hall",
                "Lockers",
                "Showers",
                "Toilet",
                "Pipes",
                "Supplies",
                "Kayaks",
                "Diving",
                "Yellow Stairs",
                "Yellow Stairs Top",
                "Tunnel",
                "White Stairs",
            ],
        },

        {
            name: "1st Floor",
            callouts: [
                "Reception",
                "Archives",
                "Coast Guard",
                "Radio",
                "Radio Hall",
                "Yellow Stairs",
                "Coast Guard Hall",
                "Lounge",
                "Blue Stairs Bottom",
                "Blue Stairs",
                "White Stairs",
                "Lower Bridge / Old Bridge",
                "Model",
                "Security",
                "Map Room",
                "Projector",
                "Kitchen",
                "Map Room Hall",
                "Green Stairs",
                "Green Stairs Bottom",
                "Museum",
                "Red Stairs",
                "Red Hall",
            ],
        },

        {
            name: "2nd Floor",
            callouts: [
                "Museum",
                "Map Room Hall",
                "Red Stairs",
                "Red Hall",
                "Roof Entrance",
                "90",
                "Green Hall",
                "Green Stairs Top",
                "Green Stairs",
                "Server",
                "Control",
                "Radar",
                "Renovation / Blue Tarp",
                "Renovation Wall / Blue Tarp Wall",
                "Upper Bridge",
                "Printer",
                "Blue Stairs",
                "Blue Stairs Bottom",
                "Radio Hall",
                "Yellow Stairs Top",
            ],
        },
    ],
};

export default kanal;
