const oregon = {
    mapName: "Oregon",
    floors: [
        {
            name: "Basement",
            callouts: [
                "Blue",
                "Pillar Hall",
                "Pillar",
                "Harry Potter",
                "Back Stairs",
                "Electrical",
                "Supply",
                "Supply Closet",
                "Supply Breach",
                "Long Hall (Basement Hall)",
                "Freezer",
                "Freezer Stairs",
                "Laundry",
                "Laundry Rotate",
                "Laundry Storage",
                "Laundry Stairs",
            ],
        },

        {
            name: "1st Floor",
            callouts: [
                "Small Tower",
                "Small Tower Stairs",
                "Top Small Tower",
                "Small Tower Office",
                "Showers Hall",
                "Showers",
                "Dining",
                "Dining Hall",
                "90",
                "Kitchen",
                "Kitchen Hall",
                "Rear Stage",
                "Back Stairs",
                "Big Tower Stairs",
                "Meeting Stage",
                "Meeting",
                "Split",
                "Zulu",
                "Lobby",
                "Garage",
                "Lobby Stairs",
                "Laundry Stairs",
                "Classroom",
                "Security Hall",
                "Freezer Stairs",
                "Security",
                "Bottom White",
                "White Stairs",
            ],
        },

        {
            name: "2nd Floor",
            callouts: [
                "Armory",
                "Armory Hall",
                "Trophy",
                "Bedroom",
                "Bedroom Balcony",
                "Bedroom Closet",
                "Main hall",
                "Games",
                "Lower attic",
                "Attic",
                "Big Tower",
                "Bunks",
                "Big Window",
                "White Stairs",
                "Kids",
            ],
        },
    ],
};

export default oregon;
