const skyscraper = {
    mapName: "Skyscraper",
    floors: [
        {
            name: "1st Floor",
            callouts: [
                "Side Entrance",
                "House Lobby",
                "Bedroom",
                "Bedroom Closet",
                "Walk-in",
                "Bathroom",
                "House Stairs",
                "Reception",
                "Recetion Desk",
                "Delivery",
                "Showers",
                "Coat Check",
                "Bar",
                "Bar Desk",
                "Sushi",
                "Sushi Small Desk",
                "Sushi Desk",
                "Pantry",
                "Kitchen",
                "BBQ",
                "Sushi Stairs",
                "Restaurant",
                "Stage",
                "Toilet",
                "Back Hall",
                "Back Stairs",
            ],
        },

        {
            name: "2nd Floor",
            callouts: [
                "House Stairs",
                "VIP",
                "Exhibition",
                "Display",
                "Office",
                "Lounge Desk",
                "Lounge",
                "Office Balcony",
                "East Balcony",
                "Display Balcony",
                "VIP Balcony",
                "Dragon",
                "Shrine",
                "Shrine Balcony",
                "Terrace",
                "Drum",
                "Catwalk",
                "Shrine Connector",
                "Tea Room",
                "Long Hall",
                "Top Back Stairs",
                "Back Stairs",
                "Karaoke",
                "Karaoke Rotate",
                "Geisha Hall",
                "Geisha",
                "Geisha Balcony",
                "Geisha Hatch",
                "Short Hall",
                "Sushi Stairs",
                "Drum Box",
                "Tea Half Wall",
            ],
        },
    ],
};

export default skyscraper;
