const stadium = {
    mapName: "Stadium Bravo",
    floors: [
        {
            name: "1st Floor",
            callouts: [
                "Ventilation",
                "Ventilation Hall",
                "Servers",
                "Showers",
                "Main Stairs",
                "Lobby",
                "Showers Hall",
                "Tellers",
                "Tellers Entrance",
                "Toilets",
                "Delivery",
                "Supply",
                "Kitchen Hall",
                "Kitchen",
                "Sunrise Hall",
                "Blue Stairs",
                "Sunrise",
                "Sunrise Entrance",
            ],
        },

        {
            name: "2nd Floor",
            callouts: [
                "Armory",
                "Armory Desk",
                "Archives",
                "Office",
                "Fountain",
                "Hookah Connector",
                "Hookah",
                "Main Stairs",
                "Armory Balcony",
                "Penthouse",
                "Bathroom",
                "Guitar",
                "VIP Hall",
                "VIP",
                "Hookah Hall",
                "Blue Stairs",
                "Hookah Balcony",
                "Hookah Bridge",
                "VIP Balcony",
                "Guitar Balcony",
                "Penthouse Balcony",
                "East Balcony",
                "Office Balcony",
            ],
        },
    ],
};

export default stadium;
