const themePark = {
    mapName: "Theme Park",
    floors: [
        {
            name: "1st Floor",
            callouts: [
                "Gong",
                "Maintenance",
                "Dragon",
                "Red Corridor",
                "Red 90",
                "Locker",
                "Tellers",
                "Throne Room",
                "Armory",
                "Blue",
                "Joint Corridor (Blue Entrance)",
                "Joint Corridor (Lab Entrance)",
                "Arcade Entrance",
                "Arcade Stairs",
                "Barrel",
                "Lab",
                "Storage",
                "Toilet",
                "Yellow 90",
                "Yellow Stairs",
                "Armory Wall",
                "Dragon Stairs",
            ],
        },

        {
            name: "2nd Floor",
            callouts: [
                "Upper Arcade",
                "Cafe Corridor",
                "Cafe",
                "Day Care",
                "Yellow Corridor (2F)",
                "Top Yellow",
                "Bunk",
                "Break Room",
                "Upper Arcade Hallway",
                "Waiting Room",
                "Initiation",
                "Office",
                "Vault",
                "Showers",
                "Cash",
                "Cash Corridor",
                "Control",
                "Dragon Stairs Top",
                "Cash Balcony",
            ],
        },
    ],
};

export default themePark;
