const villa = {
    mapName: "Villa",
    floors: [
        {
            name: "Basement",
            callouts: [
                "Basement Office",
                "Art Storage",
                "Wine Cellar",
                "Pantry Stairs",
                "Pantry",
                "Cellar Tunnel",
                "Basement Hall",
                "Tasting",
                "Crypt Tunnel",
                "Bottom Red Stairs",
                "Basement Back Stairs",
                "Astro Stairs",
                "Astro",
            ],
        },

        {
            name: "1st Floor",
            callouts: [
                "Main Entrance",
                "Main",
                "Main Stairs",
                "Art",
                "Piano",
                "Piano Hall North",
                "Piano 90",
                "Piano Hall West",
                "Library",
                "1F Toilet",
                "Living Room",
                "Gallery",
                "Living Room Hall",
                "Bottom Red Stairs",
                "Mid Red Stairs",
                "Skylight Hall",
                "Skylight 90",
                "Back Hall",
                "Mud",
                "Memorial",
                "Bikes",
                "Dining",
                "Laundry",
                "Kitchen",
                "Pantry",
                "Pantry Stairs",
                "Kitchen Entrance",
                "Basement Back Stairs",
                "Astro Stairs",
                "Astro",
            ],
        },

        {
            name: "2nd Floor",
            callouts: [
                "Main Entrance",
                "Main",
                "Main Stairs",
                "Main Stairs Top",
                "Study",
                "Veranda",
                "Study Window",
                "Aviator",
                "Bault",
                "Games",
                "Classical West",
                "Classical 90",
                "Classical North",
                "Landing",
                "Top Red Stairs",
                "Mid Red Stairs",
                "Landing Sofa",
                "Statue",
                "Statue Table",
                "Bedroom",
                "Closet",
                "Bathroom",
                "Bedroom Balcony",
                "Astro",
                "Astro Stairs",
                "Trophy",
                "Trophy Double Door / Wolf",
                "Stable Balcony",
            ],
        },
    ],
};

export default villa;
